Worlds:
- All
Scanner:
  event:
    onPlayerJoin: 1
    onChunkLoad: 0.1
Bans:
  Usage:
  - 19
  Ownership:
  - 7
  World:
Messages:
  labels:
    7: Bedrock
    19: Sponge
  reasons:
    7: Bedrock should not be mined
    19: Sponge is only usable by donors