Worlds:
- All
Scanner:
  event:
    onPlayerJoin: 1
    onChunkLoad: 0.1
Bans:
  Usage:
  - 19
  Ownership:
  - 7
  - 35-6
  World:
Messages:
  labels:
    7: Bedrock
    19: Sponge
    35-6: Pink Wool
  reasons:
    7: Bedrock should not be mined
    19: Sponge is only usable by donors
    35-6: Pink wool is too awesome for you