TekkitCustomizer:
  ProtectSurfaceFromExplosives: true
  RemoveUUMatterToNonRenewableItemRecipes: true
  EnforcementWorlds:
  - world
  - world_nether
  - world_the_end
  Bans:
    UsageBanned:
    - 27585:2:Divining Rod III:Makes mining trivial, undermining the server economy.
    - 27526:*:Philosopher's Stone:Bypasses anti-grief to change blocks in protected areas without permission.
    OwnershipBanned:
    - 27556:*:Catalytic Lens:Bypasses anti-grief to change blocks in protected areas without permission.
    - 27527:*:Destruction Catalyst:Bypasses anti-grief to change blocks in protected areas without permission.
    - 27530:*:Evertide Amulet:Bypasses anti-grief to place water in protected areas without permission.
    - 27579:*:Infernal Armor:Bypasses anti-grief to destroy blocks in protected areas without permission.
    - 27580:*:Abyss Helmet:Calls lightning to injure players even when PvP is off.
    - 27537:*:Harvest Goddess Band:Bypasses anti-grief to grow and harvest in protected areas without permission.
    - 27532:*:Black Hole Band:Bypasses anti-grief to remove water in protected areas without permission.
    - 27533:*:Ring of Ignition:Bypasses anti-grief to injure claimed animals and set fires in protected areas without permission.  May injure players even when PvP is off.
    - 27593:*:Void Ring:Key ingredient in an item duplication exploit.
    - 27583:*:Mercurial Eye:Bypasses anti-grief to change blocks in protected areas without permission.
    - 27584:*:Ring of Arcana:Bypasses anti-grief to change blocks in protected areas without permission.
    - 27536:*:Swiftwolf's Ring:Calls lightning to injure players even when PvP is off, and the knockback effect enables animal theft.
    - 27538:*:Watch of Flowing Time:Can be used to sabotage another player's automated processes by altering speed of components.
    - 27531:*:Volcanite Amulet:Bypasses anti-grief to place lava in protected areas without permission.
    - 27546:*:Dark Matter Sword:Power attack injures players when PvP is off, and protected animals without permission.
    - 27543:*:Dark Matter Pickaxe:Bypasses anti-grief to collect ore in protected areas without permission.
    - 27544:*:Dark Matter Shovel:Bypasses anti-grief to break blocks in protected areas without permission.
    - 27545:*:Dark Matter Hoe:Bypasses anti-grief to change blocks in protected areas without permission.
    - 27547:*:Dark Matter Axe:Bypasses anti-grief to break blocks in protected areas without permission.
    - 27555:*:Dark Matter Hammer:Bypasses anti-grief to break blocks in protected areas without permission.
    - 27564:*:Red Matter Pickaxe:Bypasses anti-grief to collect ores in protected areas without permission.
    - 27565:*:Red Matter Shovel:Bypasses anti-grief to break blocks in protected areas without permission.
    - 27566:*:Red Matter Hoe:Bypasses anti-grief to change blocks in protected areas without permission.
    - 27567:*:Red Matter Sword:Power attack injuures players when PvP is off, and protected animals without permission.
    - 27568:*:Red Matter Axe:Bypasses anti-grief to break blocks in protected areas without permission.
    - 27570:*:Red Matter Hammer:Bypasses anti-grief to break blocks in protected areas without permission.
    - 27572:*:Red Matter Katar:Bypasses anti-grief to change blocks in protected areas without permission, and may injure players even when PvP is off.
    - 27573:*:Red Matter Morning Star:Bypasses anti-grief to change blocks in protected areas without permission, and may injure players even when PvP is off.
    - 126:4:Red Matter Furnace:Key ingredient in an item duplication exploit.
    - 26524:*:Cannon:Bypasses anti-grief to break blocks in protected areas without permission.
    - 126:10:Nova Catalyst:Bypasses anti-grief to break blocks in protected areas without permission.
    - 126:11:Nova Cataclysm:Bypasses anti-grief to break blocks in protected areas without permission.
    - 4095:*:Dimensional Anchor:Can easily crash the server by consuming all hard drive allocation.
    - 7312:*:Tank Cart:Key ingredient in an item duplication exploit.
    - 216:*:Turtle:Bypasses anti-grief to build in protected areas without permission.
    - 150:12:Igniter:Bypasses anti-grief to set fire in protected areas without permission.
    - 214:0:World Anchor:Consumes extra server memory, which may slow or crash the server.
    - 7303:*:Anchor Cart:Consumes extra server memory, which may slow or crash the server.
    - 213:11:Feed Station:Unattended animal breeding can result in animal overload, severely slowing the server.
    - 7310:*:Tunnel Bore:The Tunnel Bore bypasses anti-grief to break blocks in protected areas without permission.
    - 7308:*:Iron Bore Head:The Tunnel Bore bypasses anti-grief to break blocks in protected areas without permission.
    - 7272:*:Steel Bore Head:The Tunnel Bore bypasses anti-grief to break blocks in protected areas without permission.
    - 7314:*:Diamond Bore Head:The Tunnel Bore bypasses anti-grief to break blocks in protected areas without permission.
    - 173:3:Project Table:May craft banned items which would then be confiscated, wasting your ingredients.
    - 169:*:Automatic Crafting Table:May craft banned items which would then be confiscated, wasting your ingredients.
    - 194:1:Automatic Crafting Table MkII:May craft banned items which would then be confiscated, wasting your ingredients.
    - 7281:*:Work Cart:May craft banned items which would then be confiscated, wasting your ingredients.
    - 192:1:Industrial Alarm:May be turned up very loud and then hidden or protected to grief players.
    - 192:2:Howler Alarm:May be turned up very loud and then hidden or protected to grief players.
    - 150:7:Frame Motor:Bypasses anti-grief to move blocks into and out of protected areas without permission.
    - 127:*:Dark Matter Pedestal:Fills the server log very quickly when activated, potentially running the server out of storage allocation and causing a crash.
    - 126:0:Energy Collector I:Converting renewable energy sources to non-renewable ores undermines the server economy.
    - 126:1:Energy Collector II:Converting renewable energy sources to non-renewable ores undermines the server economy.
    - 126:2:Energy Collector III:Converting renewable energy sources to non-renewable ores undermines the server economy.
    - 30208:*:Mining Laser:May catch other players on fire even when PvP is off.
    - 223:1:Tesla Coil:May kill other players even when PvP is off.
    - 26498:*:Wooden Hammer:The power attack injures protected animals without permission, and players even when PvP is off.
    - 26499:*:Stone Hammer:The power attack injures protected animals without permission, and players even when PvP is off.
    - 26500:*:Iron Hammer:The power attack injures protected animals without permission, and players even when PvP is off.
    - 26501:*:Diamond Hammer:The power attack injures protected animals without permission, and players even when PvP is off.
    - 26502:*:Golden Hammer:The power attack injures protected animals without permission, and players even when PvP is off.
    PlacementBanned: []
    WorldBanned: []
    CraftingBanned: []