#RemoveUUMatterToNonRenewableItemRecipes: true
Worlds:
- world
- world_nether
- world_the_end
Bans:
  Usage:
  - 27585-2
  - 27526
  Ownership:
  - 27556
  - 27527
  - 27530
  - 27579
  - 27580
  - 27537
  - 27532
  - 27533
  - 27593
  - 27583
  - 27584
  - 27536
  - 27538
  - 27531
  - 27546
  - 27543
  - 27544
  - 27545
  - 27547
  - 27555
  - 27564
  - 27565
  - 27566
  - 27567
  - 27568
  - 27570
  - 27572
  - 27573
  - 126-4
  - 26524
  - 126-10
  - 126-11
  - 4095
  - 7312
  - 216
  - 150-12
  - 214-0
  - 7303
  - 213-11
  - 7310
  - 7308
  - 7272
  - 7314
  - 173-3
  - 169
  - 194-1
  - 7281
  - 192-1
  - 192-2
  - 150-7
  - 127
  - 126-0
  - 126-1
  - 126-2
  - 30208
  - 223-1
  - 26498
  - 26499
  - 26500
  - 26501
  - 26502
  Placement:
  World:
  Crafting:
Messages:
  shortname:
    27585-1: Divining Rod III
    27526: Philosopher's Stone
    27556: Catalytic Lens
    27527: Destruction Catalyst
    27530: Evertide Amulet
    27579: Infernal Armor
    27580: Abyss Helmet
    27537: Harvest Goddess Band
    27532: Black Hole Band
    27533: Ring of Ignition
    27593: Void Ring
    27583: Mercurial Eye
    27584: Ring of Arcana
    27536: Swiftwolf's Ring
    27538: Watch of Flowing Time
    27531: Volcanite Amulet
    27546: Dark Matter Sword
    27543: Dark Matter Pickaxe
    27544: Dark Matter Shovel
    27545: Dark Matter Hoe
    27547: Dark Matter Axe
    27555: Dark Matter Hammer
    27564: Red Matter Pickaxe
    27565: Red Matter Shovel
    27566: Red Matter Hoe
    27567: Red Matter Sword
    27568: Red Matter Axe
    27570: Red Matter Hammer
    27572: Red Matter Katar
    27573: Red Matter Morning 
    126-4: Red Matter Furnace
    26524: Cannon
    126-10: Nova Catalyst
    126-11: Nova Cataclysm
    4095: Dimensional Anchor
    7312: Tank Cart
    216: Turtle
    150-12: Igniter
    214: World Anchor
    7303: Anchor Cart
    213: Feed Station
    7310: Tunnel Bore
    7308: Iron Bore Head
    7272: Steel Bore Head
    7314: Diamond Bore Head
    173: Project Table
    169: Automatic Crafting Table
    194: Automatic Crafting Table MkII
    7281: Work Cart
    192: Industrial Alarm
    192: Howler Alarm
    150-7: Frame Motor
    127: Dark Matter Pedestal
    126-0: Energy Collector I
    126-1: Energy Collector II
    126-2: Energy Collector III
    30208: Mining Laser
    223: Tesla Coil
    26498: Wooden Hammer
    26499: Stone Hammer
    26500: Iron Hammer
    26501: Diamond Hammer
    26502: Golden Hammer
  reason:
    27585-1: Makes mining trivial, undermining the server economy.
    27526: Bypasses anti-grief to change blocks in protected areas without permission.
    27556: Bypasses anti-grief to change blocks in protected areas without permission.
    27527: Bypasses anti-grief to change blocks in protected areas without permission.
    27530: Bypasses anti-grief to place water in protected areas without permission.
    27579: Bypasses anti-grief to destroy blocks in protected areas without permission.
    27580: Calls lightning to injure players even when PvP is off.
    27537: Bypasses anti-grief to grow and harvest in protected areas without permission.
    27532: Bypasses anti-grief to remove water in protected areas without permission.
    27533: Bypasses anti-grief to injure claimed animals and set fires in protected areas without permission. May injure players even when PvP is off.
    27593: Key ingredient in an item duplication exploit.
    27583: Bypasses anti-grief to change blocks in protected areas without permission.
    27584: Bypasses anti-grief to change blocks in protected areas without permission.
    27536: Calls lightning to injure players even when PvP is off, and the knockback effect enables animal theft.
    27538: Can be used to sabotage another player's automated processes by altering speed of components.
    27531: Bypasses anti-grief to place lava in protected areas without permission.
    27546: Power attack injures players when PvP is off, and protected animals without permission.
    27543: Bypasses anti-grief to collect ore in protected areas without permission.
    27544: Bypasses anti-grief to break blocks in protected areas without permission.
    27545: Bypasses anti-grief to change blocks in protected areas without permission.
    27547: Bypasses anti-grief to break blocks in protected areas without permission.
    27555: Bypasses anti-grief to break blocks in protected areas without permission.
    27564: Bypasses anti-grief to collect ores in protected areas without permission.
    27565: Bypasses anti-grief to break blocks in protected areas without permission.
    27566: Bypasses anti-grief to change blocks in protected areas without permission.
    27567: Power attack injuures players when PvP is off, and protected animals without permission.
    27568: Bypasses anti-grief to break blocks in protected areas without permission.
    27570: Bypasses anti-grief to break blocks in protected areas without permission.
    27572: Bypasses anti-grief to change blocks in protected areas without permission, and may injure players even when PvP is off.
    27573: Bypasses anti-grief to change blocks in protected areas without permission, and may injure players even when PvP is off.
    126-4: Key ingredient in an item duplication exploit.
    26524: Bypasses anti-grief to break blocks in protected areas without permission.
    126-10: Bypasses anti-grief to break blocks in protected areas without permission.
    126-11: Bypasses anti-grief to break blocks in protected areas without permission.
    4095: Can easily crash the server by consuming all hard drive allocation.
    7312: Key ingredient in an item duplication exploit.
    216: Bypasses anti-grief to build in protected areas without permission.
    150-12: Bypasses anti-grief to set fire in protected areas without permission.
    214-0: Consumes extra server memory, which may slow or crash the server.
    7303: Consumes extra server memory, which may slow or crash the server.
    213-11: Unattended animal breeding can result in animal overload, severely slowing the server.
    7310: The Tunnel Bore bypasses anti-grief to break blocks in protected areas without permission.
    7308: The Tunnel Bore bypasses anti-grief to break blocks in protected areas without permission.
    7272: The Tunnel Bore bypasses anti-grief to break blocks in protected areas without permission.
    7314: The Tunnel Bore bypasses anti-grief to break blocks in protected areas without permission.
    173-3: May craft banned items which would then be confiscated, wasting your ingredients.
    169: May craft banned items which would then be confiscated, wasting your ingredients.
    194-1: May craft banned items which would then be confiscated, wasting your ingredients.
    7281: May craft banned items which would then be confiscated, wasting your ingredients.
    192-1: May be turned up very loud and then hidden or protected to grief players.
    192-2: May be turned up very loud and then hidden or protected to grief players.
    150-7: Bypasses anti-grief to move blocks into and out of protected areas without permission.
    127: Fills the server log very quickly when activated, potentially running the server out of storage allocation and causing a crash.
    126-0: Converting renewable energy sources to non-renewable ores undermines the server economy.
    126-1: Converting renewable energy sources to non-renewable ores undermines the server economy.
    126-2: Converting renewable energy sources to non-renewable ores undermines the server economy.
    30208: May catch other players on fire even when PvP is off.
    223-1: May kill other players even when PvP is off.
    26498: The power attack injures protected animals without permission, and players even when PvP is off.
    26499: The power attack injures protected animals without permission, and players even when PvP is off.
    26500: The power attack injures protected animals without permission, and players even when PvP is off.
    26501: The power attack injures protected animals without permission, and players even when PvP is off.
    26502: The power attack injures protected animals without permission, and players even when PvP is off.