version: 1.2
name: ItemRestrict
main: info.terrismc.itemrestrict.ItemRestrict
author: krisdestruction
description: Ban items and blocks for Bukkit, Tekkit, and FTB servers using the Bukkit API
commands:
  ires:
    description: Get plugin help
    usage: /ires
    permission: itemrestrict.help
  ires reload:
    description: Reloads the config files
    usage: /ires reload
    permission: itemrestrict.reload
permissions:
  itemrestrict.admin:
    description: Grants all administrative privileges.
    children:
      itemrestrict.help: true
      itemrestrict.reload: true
  itemrestrict.help:
      description: Grants permission to access help root
      default: op
  itemrestrict.reload:
      description: Grants permission to reload the config
      default: op