version: 1.0
name: ItemRestrict
main: info.terrismc.ItemRestrict.ItemRestrict
author: krisdestruction
description: Ban items and blocks for Bukkit, Tekkit, and FTB servers using the Bukkit API
commands:
   blockinfo:
      description: Provides type ID and damage information for a material in the world or in hand.
      usage: /BlockInfo
      permission: itemrestrict.blockinfo   
   reloadbanneditems:
      description: Reloads the banned item list from the config file.
      usage: /ReloadBannedItems
      permission: itemrestrict.reload
permissions:
    itemrestrict.admin.*:
        description: Grants all administrative privileges.
        children:
            itemrestrict.blockinfo: true
            itemrestrict.reload: true
    itemrestrict.*:
        description: Grants permission to bypass all bans.
        default: op
    itemrestrict.blockinfo:
        description: Grants permission to use /BlockInfo.
        default: op
    itemrestrict.reload:
        description: Grants permission to use /ReloadBannedItems.
        default: op